language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit

script:
  - cp ./app/config/parameters.yml.dist ./app/config/parameters.yml
  - ./bin/behat @WshCmsBundle
