<?php

namespace Wsh\CmsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Language repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Language extends EntityRepository
{
    /**
     * @param bool $simpleArray If true returns an array of languageCode => languageName
     * @return array
     */
    public function findByEnabled($simpleArray = false)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('Language')
            ->from('WshCmsBundle:Language', 'Language')
            ->where('Language.enabled = true')
            ->orderBy('Language.name', 'ASC');
        $results = $qb->getQuery()->getResult();

        if ($simpleArray) {
            $results = array_combine(
                array_map(
                    function ($lang) {
                        return $lang->getCode();
                    },
                    $results
                ),
                array_map(
                    function ($lang) {
                        return $lang->getName();
                    },
                    $results
                )
            );
        }

        return $results;
    }
}
