<?php

namespace Wsh\CmsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Language repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Language extends EntityRepository
{
    /**
     * @param bool $simpleArray If true returns an array of languageCode => languageName
     * @return array
     */
    public function findByEnabled($simpleArray = false)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('Language')
            ->from('WshCmsBundle:Language', 'Language')
            ->where('Language.enabled = true')
            ->orderBy('Language.name', 'ASC');
        $results = $qb->getQuery()->getResult();

        return $simpleArray ? $this->convertToSimpleArray($results) : $results;
    }

    public function findAll($simpleArray = false)
    {
        $results = parent::findAll();
        return $simpleArray ? $this->convertToSimpleArray($results) : $results;
    }

    /**
     * @param array $array An array of Language objects
     * @return array An array of languageCode => languageName
     */
    private function convertToSimpleArray($array)
    {
        return array_combine(
            array_map(
                function ($lang) {
                    return $lang->getCode();
                },
                $array
            ),
            array_map(
                function ($lang) {
                    return $lang->getName();
                },
                $array
            )
        );
    }
}
