<?php

namespace Wsh\CmsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Page repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Page extends EntityRepository
{
}
