wsh_cms_html:
    resource: "@WshCmsHtmlBundle/Controller/"
    type:     annotation
    prefix:   /html

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

login_check:
    pattern: /admin/login_check

logout:
    pattern: /admin/logout

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_admin_dashboard:
    pattern: /admin
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

_imagine:
    resource: .
    type:     imagine
