services:

  # --- Entity Repositories ---

  repository.language:
      class: Wsh\CmsBundle\Entity\Repository\Language
      factory_service: doctrine
      factory_method:  getRepository
      arguments:
          - WshCmsBundle:Language

  repository.page:
      class: Wsh\CmsBundle\Entity\Repository\Page
      factory_service: doctrine
      factory_method:  getRepository
      arguments:
          - WshCmsBundle:Page

  repository.translation:
        class: Gedmo\Translatable\Entity\Repository\TranslationRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:
            - Gedmo\Translatable\Entity\Translation