services:

  # --- Event Listeners ---

  kernel.listener.your_listener_name:
      class: Wsh\CmsBundle\Listener\Locale
      arguments:
          container: "@service_container"
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
